# Generated by Django 5.2.1 on 2025-05-30 21:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_recipe_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="tags",
        ),
        migrations.AlterModelOptions(
            name="favorite",
            options={
                "ordering": [],
                "verbose_name": "Избранное",
                "verbose_name_plural": "Избранное",
            },
        ),
        migrations.AlterModelOptions(
            name="shoppingcart",
            options={
                "ordering": [],
                "verbose_name": "Список покупок",
                "verbose_name_plural": "Списки покупок",
            },
        ),
        migrations.AlterField(
            model_name="recipe",
            name="cooking_time",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(32000),
                ],
                verbose_name="Время приготовления (мин)",
            ),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="amount",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(32000),
                ],
                verbose_name="Количество",
            ),
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
