# Generated by Django 5.2.1 on 2025-05-30 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_recipe_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="tags",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
