# Generated by Django 5.2.1 on 2025-05-30 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_recipe_tags_alter_favorite_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="favorite",
            options={
                "ordering": ["-recipe__pub_date"],
                "verbose_name": "Избранное",
                "verbose_name_plural": "Избранное",
            },
        ),
        migrations.AlterModelOptions(
            name="shoppingcart",
            options={
                "ordering": ["-recipe__pub_date"],
                "verbose_name": "Список покупок",
                "verbose_name_plural": "Списки покупок",
            },
        ),
    ]
