volumes:
  pg_data:
  static:
  media:
  docs:
  frontend_build:

networks:
  foodgram-network:
    driver: bridge
    name: foodgram-network

services:

  db:
    image: postgres:14
    container_name: db
    hostname: db
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data/
    networks:
      - foodgram-network

  backend:
    container_name: foodgram-back
    build: ../backend/
    env_file: ../.env
    volumes:
      - static:/app/staticfiles/
      - media:/app/media/
      - docs:/app/docs/
    depends_on:
      - db
      - frontend
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn backend.wsgi --bind 0.0.0.0:8000"
    networks:
      - foodgram-network

  frontend:
    container_name: foodgram-front
    build: 
      context: ../frontend/
      dockerfile: Dockerfile
    env_file: ../.env
    volumes:
      - static:/static/
      - docs:/app/docs/
      - frontend_build:/frontend_build
    networks:
      - foodgram-network

  nginx:
    image: nginx:1.25.4-alpine
    container_name: foodgram-nginx
    env_file: ../.env
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/app/staticfiles/
      - media:/app/media/
      - docs:/app/docs/
      - frontend_build:/usr/share/nginx/html
    depends_on:
      - backend
      - frontend
    networks:
      - foodgram-network