
version: '3.9'

services:
  frontend:
    container_name: foodgram-front
    build: ../frontend
    volumes:
      - ../frontend/:/app/result_build/

  backend:
    build:
      context: ../backend
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static:/app/static
      - media:/app/media
    env_file:
      - ../.env
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    env_file:
      - ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data

  nginx:
    image: nginx:1.25
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend_build:/usr/share/nginx/html
      - static:/app/static
      - media:/app/media
    depends_on:
      - backend

volumes:
  pg_data:
  static:
  media:
  frontend_build: